# Generated by Django 6.0.2 on 2026-02-20 17:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='cookingMethod',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='optionalIngredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='food',
            name='prepTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='recipe',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='taste',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
