# Generated by Django 6.0.2 on 2026-02-20 17:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_food_ingredients_remove_food_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='mainIngredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
    ]
