# Generated by Django 6.0.2 on 2026-02-20 17:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_food_mainingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='cookingMethod',
        ),
        migrations.RemoveField(
            model_name='food',
            name='mainIngredients',
        ),
        migrations.RemoveField(
            model_name='food',
            name='optionalIngredients',
        ),
        migrations.RemoveField(
            model_name='food',
            name='prepTime',
        ),
        migrations.AddField(
            model_name='food',
            name='cooking_method',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='main_ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='food',
            name='optional_ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='food',
            name='prep_time',
            field=models.IntegerField(null=True),
        ),
    ]
